# Generated by Django 4.2.2 on 2023-06-12 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preveducationmodel',
            name='address',
        ),
        migrations.DeleteModel(
            name='StudentContactDetailModel',
        ),
        migrations.RemoveField(
            model_name='studentpreveducationmodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentpreveducationmodel',
            name='student',
        ),
        migrations.DeleteModel(
            name='AddressDetailModel',
        ),
        migrations.DeleteModel(
            name='PrevEducationModel',
        ),
        migrations.DeleteModel(
            name='StudentDetailModel',
        ),
        migrations.DeleteModel(
            name='StudentPrevEducationModel',
        ),
    ]
