# Generated by Django 4.2.2 on 2023-06-14 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrevEducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('percentage', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_education_address', to='students.addressdetailmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentContactDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('father_number', models.CharField(max_length=15)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_number', models.CharField(max_length=15)),
                ('student_number', models.CharField(max_length=15)),
                ('gmail', models.EmailField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField(unique=True)),
                ('date_of_birth', models.DateField()),
                ('branch', models.CharField(max_length=100)),
                ('year_of_joining', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_detail_address', to='students.addressdetailmodel')),
                ('prev_education', models.ManyToManyField(blank=True, related_name='student_prev_education_field', to='students.preveducationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPrevEducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('percentage', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_prev_education_address', to='students.addressdetailmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_prev_education', to='students.studentdetailmodel')),
            ],
        ),
    ]
