# Generated by Django 4.2.2 on 2023-06-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentdetailmodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetailmodel',
            name='prev_education',
            field=models.ManyToManyField(blank=True, related_name='student_prev_education_field', to='students.preveducationmodel'),
        ),
    ]
